error code
py$ python Wall_half_NN.py
before 1st layer
before 2nd layer
before 5th layer
before poor flat
befor sigmoid
befor dropout
befor readout
befor y_CNV
befor tf.name_scope
befor scope train
befor merge all
NetWorkMaking Fin
before if readfile: half_img/rt_116.jpg
passed if
(76800,)
(76800,)
Traceback (most recent call last):
  File "Wall_half_NN.py", line 169, in <module>
    result=sess.run([merged, difference], feed_dict=feed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 372, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 625, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (76800,) for Tensor u'input:0', which has shape '(?, 76800)'